# Site settings
title: civic studio
email: civicstudio@gvsu.edu
description: practicing and presenting art in public contexts.
<<<<<<< HEAD
baseurl: "/civtest"
url: 
=======
url: 
baseurl: /civstudio
>>>>>>> 0cab32f2e2ba207abb7a15ab931d4043a3c7194e
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

plugins:
- jekyll-paginate

# Ideal image slider
iis_slider_array: []

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


